### ISSUE TITLE
creating a mapless model from a json string

### ISSUE THREAD

**Issue by alexisargyris** [flow-stack/MiniMapless#8]
Hello,

This statement

`MaplessModel fromJSONString: '{"name": "abcd"}'`

returns nil. Is this correct? What is the recommended way to create a model starting from a json string?

Thanks in a advance

**Comment by sebastianconcept** [comment]
Oh hi @alexisargyris, I see what happens.

Mapless always include 1 attribute of metadata: `modelClass`
You'll see that in every mapless instance serialized to JSON.
That's the way they know which kind of mapless the JSON should be matching. 

See some examples:

As you said:
	`MaplessModel fromJSONString: '{"name": "abcd"}'. nil`
	
But this one would return `a Product` (assuming you have `Product` as subclass of `MaplesModel`):
	`Product fromJSONString: '{"name": "abcd", "modelClass":"Product"}'. a Product` 

Because they know the class, this would also work:
	`Mapless fromJSONString: '{"name": "abcd", "modelClass":"Product"}'.  a Product`

I'm closing this issue but feel free to ask more and let me know if you want an invite to the `http://flow-stack.slack.com` group

**Comment by alexisargyris** [comment]
oh, i see, thanks very much for the explanation

if flow-stack is a way of informal communication, then yes please, do
forward an invite, mainly to avoid polluting the your repository with more
idiotic questions

thanks again

alexis

**Comment by sebastianconcept** [comment]
Glad to hear.
I don't think there are stupid questions!
We have a very friendly space, yes. 
All I need is an email address to send you the invite

**Comment by alexisargyris** [comment]
alexis.argyris at gmail.com

thanks

**Comment by sebastianconcept** [comment]
Sorry for the delay

Invite just sent!

**Comment by alexisargyris** [comment]
no prob, got in already
